### PR TITLE
Display max retries in container details view

### PR DESCRIPTION
**Pull request by tombee**
screen shot 2014-11-16 at 21 30 00
screen shot 2014-11-16 at 21 30 08

### CODE REVIEW

**Comment by ehazlett** [comment]
Could we put this in line with the restart policy.  For example, if there is a maximum restart, then put it like "on-failure:<n>"?  Would save some space and be more like Docker.

**Comment by tombee** [comment]
Sure :)

**Comment by tombee** [comment]
It now mimics the docker behaviour for max retries:

screen shot 2014-11-17 at 15 49 02screen shot 2014-11-17 at 15 49 06
screen shot 2014-11-17 at 15 49 11

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
