### PR TITLE
Replaced health column with green/red/grey status circle

### PR DESCRIPTION
**Pull request by tombee**
screen shot 2014-11-15 at 12 24 17

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks good, but I have a number of issues here;
- It's no longer possible to sort on status?
- The actual health text is removed from the rows.

I do like the _visual_ side of this, but I think this is not the right way to do this. I see this as a purely cosmetic change and because of this, it would be better to hide the texts using CSS in stead of removing them.

E.g. `<span class="health-status up" title="up">up</span>` and, using CSS, make sure that that is presented as a green dot and the text is hidden. 

I added the "title" property in this example, which may be helpful to get information about what a specific colour means.

**Comment by tombee** [comment]
Thanks @thaJeztah, agreed, I'll re-work the PR as per your comments.

**Comment by thaJeztah** [comment]
Thanks! To clarify; I'm not a maintainer or anything, just my personal notes :)

**Comment by tombee** [comment]
No worries @thaJeztah, @ehazlett had suggested to use semantic-ui labels for consistency, just makes it difficult to hide the text!

**Comment by thaJeztah** [comment]
Just out of my head, something like;

`<span class="status-icon health-status up">up</span>`

```

.status-icon {
    display: inline-block;
    overflow: hidden;
    width: 7px;
    height: 7px;
    border-radius: 50%;
    text-indent: -200px;
}

.status-icon.health-status.up { background-color: green }
.status-icon.health-status.down { background-color: red }

```

**Comment by tombee** [comment]
screen shot 2014-11-15 at 13 38 14
I'd originally done something similar to that @thaJeztah, then @ehazlett had suggested for consistency with the rest of the UI to use: http://semantic-ui.com/elements/label.html

I've made the status column sortable, and added a title attribute to the span for the status circle.  I'll have a chat with @ehazlett about how to get semantic-ui to hide the text in a label.

**Comment by ehazlett** [comment]
why do we need text in the label and hide it?  we already report the status

**Comment by thaJeztah** [comment]
Oh, sorry, missed that with "semantic" you referred to a specific implementation :)

Is it just me, or is "semantic-ui" being totally _non_ semantic?

For example:

```
<div class="ui red horizontal label">...
```

That's not semantic at all, that's just _presentation_, it tells me what it should look like and not very helpful for (for example) visually impaired people.

Something like this, on the other hand;

```
<label class="status up">..
```

Tells me what it _means_  (it's a "label", it regards "status" and the status is "up"). If I decide to change the look of the "up" status to be a _purple_, _left-aligned_ _square_ with the image of a _cat_ in it, the markup would change to:

```
<label class="status up">..
```

Or, no change at all. The _meaning_ is the same, just the way I want it to look has changed.

(Sorry for this, I was just quite taken back by calling a project "semantic" but doing exactly the opposite)

**Comment by ehazlett** [comment]
@thaJeztah ok thx

LGTM

**Comment by thaJeztah** [comment]
@ehazlett sorry if I meddled too much in this; I wasn't really aware of "semantic" being a (css) ui-framework used here.

I'm currently browsing their source to see if it's possible to use more meaningful classnames, for example by using SASS or LESS to extend their classes. (i.e., `.status-label.up === .ui.label.green`)

Not sure yet how much time I have to spend on that, but for the future, it may be worthwhile to check if that's an option. Doing this makes shipyard less dependent on a specific ui-framework and would allow switching to a different theme, without having to re-write the UI / views. At the same time, you'd be able to _use_ semantic-ui (and don't have to come up with your own styles), which is of course the right thing to do.

I'll let you know if I come up with something :)

**Pull request merged**
