### PR TITLE
Angularjs refactoring

### PR DESCRIPTION
**Pull request by tombee**
Following AngularJS guidelines by @johnpapa's https://github.com/johnpapa/angularjs-styleguide

### CODE REVIEW

**Comment by tombee** [comment]
Created this for the modularisation work I've done so far, as the next steps require more work/research into restructuring the code that's already there.

**Comment by tombee** [comment]
If these changes are still wanted, let me know and I'll rebase this PR.

**Comment by ehazlett** [comment]
Yeah go ahead and rebase and I'll make sure everything still works after merge.  If that's good, we can merge the PR.  Thanks!

**Comment by johnpapa** [comment]
cool :)

**Pull request merged**
