### PR TITLE
Separated supervisor config and Optional admin password for setup task.

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by prologic** [comment]
usage of optional `adminpw`:

```
fab -u root -h docker0 setup:adminpw=admin
```

**Comment by ehazlett** [comment]
Sorry to be picky, could we change the `adminpw` to `password`?

**Comment by prologic** [comment]
Absolutely :)

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
DONE!

**Comment by ehazlett** [comment]
Thanks!  lgtm

**Pull request merged**
