### PR TITLE
reload

### PR DESCRIPTION
**Pull request by ehazlett**
This is the re-write of Shipyard to Go.  This is just to get a discussion going.  Not yet ready for merge.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Woa that's a lot of changes :smile:

Why not create a separate branch or repo for this instead of just a PR?

**Comment by ehazlett** [comment]
@thaJeztah this is a separate branch

**Comment by ehazlett** [comment]
the current master will be tagged (for archival purposes) and then this will be merged to master when it's ready.

**Comment by thaJeztah** [comment]
LOL, I just discovered that. Renewed GitHub was acting up I think, because I couldn't find a link to a branch. LOL

**Comment by ehazlett** [comment]
@thaJeztah ha no worries

**Comment by thaJeztah** [comment]
Well, I could have sworn there were links in this previously? "...wants to merge 53 commits into **master** from **reload**".

Anyway; this is the branch: https://github.com/shipyard/shipyard/tree/reload :smile:

**Pull request merged**
