### PR TITLE
Issue #314: Added restart policy to UI

### PR DESCRIPTION
**Pull request by tombee**
screen shot 2014-11-16 at 00 06 57
screen shot 2014-11-16 at 00 07 08

### CODE REVIEW

**Comment by tombee** [comment]
Fix for issue #314

**Comment by ehazlett** [comment]
Looks good.  `on-failure` can take an optional parameter for max number of times.  Should we include that?

**Comment by tombee** [comment]
Oh right, yeah!  I'll get that done :)  Sorry, missed that.

**Comment by tombee** [comment]
@ehazlett How's this?
screen shot 2014-11-16 at 20 42 36

**Comment by ehazlett** [comment]
Do the fields "Maximum Restarts" and "Network: Container Name" only show when the corresponding modes are selected (hidden by default)?

**Comment by tombee** [comment]
Yeah they only show when the relevant option in each field is selected,  I just selected them to show how the display for each one looks.

**Comment by ehazlett** [comment]
Perfect.  Thanks!

**Pull request merged**
